### ISSUE TITLE
Crash on first sign up

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#104]
With app-arm64-v8a-release.apk v1.0.66

To reproduce:
- Uninstall the app
- Install the app again
- Connect to https://community.humhub.com/
- Click on the "Sign in/up" button

The app crashes. If you relaunch the app a second time, then the button works.

**Comment by luke-** [comment]
@PrimozRatej Can you please take a look into this?

**Comment by funkycram** [comment]
It's a Huawei P30 pro. I'll try again later and send you a video.

**Comment by funkycram** [comment]
@PrimozRatej You can download this video to see how I make it crash: https://fromsmash.com/TjLfzjwUqT-ct (the link will expire in one week).

**Comment by funkycram** [comment]
@PrimozRatej @luke- tested v1.0.67 and the bug is still present.

**Comment by PrimozRatej** [comment]
I tested and logcat it on multiple devices for v1.0.66 and v1.0.6, still can't reproduce the bug or find any strange behavior.
[logcat.txt](https://github.com/humhub/app/files/12420997/logcat.txt)

@luke-  do you also have the same problem?
@funkycram could you logcat to a device and send me the output for when the error occurs? The instructions to set up adb https://support.citrix.com/article/CTX232375/how-to-install-and-collect-adb-logs-on-android-device

**Comment by luke-** [comment]
I have the following behavior:

After uninstalling, reinstalling, I get only a black image at startup. 
Even closing and reopening the app, only shows a black image.

![image](https://github.com/humhub/app/assets/4736168/f7b38902-f31e-4abd-83f3-ba9cbc0d9b94)

I must first manually clear the data (flush cache is not enough) - then the app opens normally. 

![image](https://github.com/humhub/app/assets/4736168/8ac30ce3-7c04-4db5-84f6-3ec3fb6e343d)

After that I can log in normally without further errors.

@funkycram Do you mean "Sign in/up" in HumHub or "Connect" in the app? After "Sign in/up" the App triggers a "Request Notification Access" dialog, maybe it's related to this?

---

Tested with Samsung S20

**Comment by funkycram** [comment]
@PrimozRatej : [logcat.zip](https://github.com/humhub/app/files/12421942/logcat.zip)

@luke- "Sign in/up" in HumHub

**Comment by PrimozRatej** [comment]
https://stackoverflow.com/questions/31416568/could-someone-help-me-with-this-crash-report

**Comment by luke-** [comment]
@PrimozRatej Thats a quite old problem?
@marc-farre You can also try to delete the "data" before the first start.

**Comment by marc-farre** [comment]
> You can also try to delete the "data" before the first start.

Good idea. But I'm still having the bug, even when clearing data and cache.

If I'm the only one having this bug, then it's not a problem for me, and we can close the issue.

**Comment by PrimozRatej** [comment]
Hey, @marc-farre it is a bug, I also get it sometimes, after I log in and then quickly open up a  User menu dropdown, It seems to me that there is something like this [issue](https://stackoverflow.com/questions/9147875/webview-dont-display-javascript-windows-open/43721647#43721647) going on. I think I fixed it or at least I do not get a bug anymore on the release version of the app, could you also test it please when the new release is out, Thanks!

**Comment by luke-** [comment]
Just released v1.0.68

**Comment by marc-farre** [comment]
The bug is still present on v1.0.68.
I've cleared the cache before starting the app.

**Comment by PrimozRatej** [comment]
Could you provide me a logcat again, please, Thank you.

**Comment by marc-farre** [comment]
@PrimozRatej 
[logcat.zip](https://github.com/humhub/app/files/12485221/logcat.zip)

**Comment by PrimozRatej** [comment]
Hello @marc-farre and @luke- I think I found a problem. I tested the behavior on different versions of Flutter and it seems that the version we were building the app with so latest has this bug on the native WebView plugin. 

`v 3.13.0` Crash
`v 3.14.0` Crash
`v 3.10.0` OK
`v 3.7.0` OK

**Comment by marc-farre** [comment]
Thanks @PrimozRatej this time the bug is fixed!
